export const CHANGE_ANCHOR_RECOMMEND = "anchor/CHANGE_ANCHOR_RECOMMEND";
export const CHANGE_ANCHOR_RANKING = "anchor/CHANGE_ANCHOR_RANKING";
export const CHANGE_ANCHOR_MUSIC = "anchor/CHANGE_ANCHOR_CATEGORY";
export const CHANGE_ANCHOR_LIFE = "anchor/CHANGE_ANCHOR_LIFE";
export const CHANGE_ANCHOR_CREATE = "anchor/CHANGE_ANCHOR_CREATE";
export const CHANGE_ANCHOR_KNOWLEDGE = "anchor/CHANGE_ANCHOR_KNOWLEDGE";
export const CHANGE_ANCHOR_EMOTION = "anchor/CHANGE_ANCHOR_EMOTION";
export const CHANGE_BANNER_CATEGORY = "anchor/CHANGE_BANNER_CATEGORY";
export const CHANGE_ANCHOR_EXCELLENT = "anchor/CHANGE_ANCHOR_EXCELLENT";
export const CHANGE_CATEGORY_RANKING = "anchor/CHANGE_CATEGORY_RANKING";

export const CHANGE_CURRENT_PAGE = "anchor/CHANGE_CURRENT_PAGE";
export const CHANGE_PAGE_TOTAL = "anchor/CHANGE_PAGE_TOTAL";
