export const CHANGE_ANCHOR_RECOMMEND = "anchor/CHANGE_ANCHOR_RECOMMEND";
export const CHANGE_ANCHOR_RANKING = "anchor/CHANGE_ANCHOR_RANKING";
export const CHANGE_ANCHOR_MUSIC = "anchor/CHANGE_ANCHOR_CATEGORY";
export const CHANGE_ANCHOR_LIFE = "anchor/CHANGE_ANCHOR_LIFE";
export const CHANGE_ANCHOR_CREATE = "anchor/CHANGE_ANCHOR_CREATE";
export const CHANGE_ANCHOR_KNOWLEDGE = "anchor/CHANGE_ANCHOR_KNOWLEDGE";
export const CHANGE_ANCHOR_EMOTION = "anchor/CHANGE_ANCHOR_EMOTION";
