export const CHANGE_MESSAGE_NOTIFY = "message/CHANGE_MESSAGE_NOTIFY";
export const CHANGE_MESSAGE_AT = "message/CHANGE_MESSAGE_AT";
export const CHANGE_MESSAGE_COMMENT = "message/CHANGE_MESSAGE_COMMENT";
export const CHANGE_MESSAGE_PRIVATE = "message/CHANGE_MESSAGE_PRIVATE";
