export const CHANGE_MV_INFO = "mv/CHANGE_MV_INFO";
export const CHANGE_MV_LINK = "mv/CHANGE_MV_LINK";

export const CHANGE_HOT_COMMENT = "mv/CHANGE_HOT_COMMENT";
export const CHANGE_NEW_COMMENT = "mv/CHANGE_NEW_COMMENT";
export const CHANGE_PAGE_TOTAL = "mv/CHANGE_PAGE_TOTAL";
export const CHANGE_CURRENT_PAGE = "mv/CHANGE_CURRENT_PAGE";

export const CHANGE_SIMILAR_MV = "mv/CHANGE_SIMILAR_MV";