export const CHANGE_RANKING_LIST = "ranking/CHANGE_RANKING_LIST";
export const CHANGE_CURRENT_INDEX = "ranking/CHANGE_CURRENT_INDEX";
export const CHANGE_CURRENT_RANKING_LIST_ID =
  "ranking/CHANGE_CURRENT_RANKING_LIST_ID";
export const CHANGE_CURRENT__RANKING_LIST_TITLE_INFO =
  "ranking/CHANGE_CURRENT__RANKING_LIST_TITLE_INFO";
export const CHANGE_CURRENT_RANKING_LIST =
  "ranking/CHANGE_CURRENT_RANKING_LIST";

export const CHANGE_HOT_COMMENT = "ranking/CHANGE_HOT_COMMENT";
export const CHANGE_NEW_COMMENT = "ranking/CHANGE_NEW_COMMENT";
export const CHANGE_CURRENT_PAGE = "ranking/CHANGE_CURRENT_PAGE";
export const CHANGE_PAGE_TOTAL = "ranking/CHANGE_PAGE_TOTAL";