export const CHANGE_PLAYLIST_DETAIL = "playlist/CHANGE_PLAYLIST_DETAIL";
export const CHANGE_PLAYLIST_ARRAY = "playlist/CHANGE_PLAYLIST_ARRAY";
export const CHANGE_PLAYLIST_SUBSCRIBERS =
  "playlist/CHANGE_PLAYLIST_SUBSCRIBERS";
